YummyProject/Controllers/AdminProfileController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using YummyProject.Context;
using YummyProject.Models;

namespace YummyProject.Controllers
{
    public class AdminProfileController : Controller
    {
        YummyContext context = new YummyContext();
        public ActionResult Index()
        {
            var values = context.Admins.ToList();
            return View(values);
        }

        public ActionResult AddAdminP()
        {
            return View();
        }

        [HttpPost]
        public ActionResult AddAdminP(Admin adminpr)
        {
            if (!ModelState.IsValid)
            {
                return View(adminpr);
            }
            context.Admins.Add(adminpr);
            context.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult DeleteAdminP(int id)
        {
            var delvalue = context.Admins.Find(id);
            context.Admins.Remove(delvalue);
            context.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult UpdateAdminp(int id)
        {
            var values = context.Admins.Find(id);
            return View(values);

        }

        [HttpPost]
        public ActionResult UpdateAdminp(Admin admnp)
        {

            var value = context.Admins.Find(admnp.AdminId);
            value.NameSurname = admnp.NameSurname;
            value.UserName = admnp.UserName;
            value.Password = admnp.Password;
            value.ImageUrl = admnp.ImageUrl;

            if (!ModelState.IsValid)
            {
                return View(admnp);
            }
            context.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

YummyProject/Views/AdminProfile/AddAdminP.cshtml
@model YummyProject.Models.Admin
@{
    ViewBag.Title = "AddAdminP";
    Layout = "~/Views/AdminLayout/Index.cshtml";
}

<h2>Yeni Admin Ekleme Sayfası</h2>
<br />

<form method="post">

    <label>Resim</label>
    @Html.TextBoxFor(x => x.ImageUrl, new { @class = "form-control" })
    <p class="text-danger"> @Html.ValidationMessageFor(x => x.ImageUrl) </p>
    <br />
    <label>Adı Soyadı</label>
    @Html.TextBoxFor(x => x.NameSurname, new { @class = "form-control" })
    <p class="text-danger"> @Html.ValidationMessageFor(x => x.NameSurname) </p>
    <br />
    <label>Kullanıcı Adı</label>
    @Html.TextBoxFor(x => x.UserName, new { @class = "form-control" })
    <p class="text-danger"> @Html.ValidationMessageFor(x => x.UserName) </p>
    <br />
    <label>Şifre</label>
    @Html.TextBoxFor(x => x.Password, new { @class = "form-control" })
    <p class="text-danger"> @Html.ValidationMessageFor(x => x.Password) </p>
    <br />

    <button class="btn btn-outline-success">Kaydet</button>
    <a href="@Url.Action("Index", "AdminProfile")" class="btn btn-outline-danger">İptal</a>

</form>

YummyProject/Views/AdminProfile/Index.cshtml
@model List<YummyProject.Models.Admin>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/AdminLayout/Index.cshtml";
}

<h2>Admin Profil Bilgileri</h2>
<br />

<table class="table table-bordered">

    <thead>

        <tr>
            <th>Resim</th>
            <th>Adı Soyadı</th>
            <th>Kullanıcı Adı</th>
            <th>Sil</th>
            <th>Güncelle</th>
        </tr>

    </thead>

    <tbody>
        @if (Model != null && Model.Any())
        {
            foreach (var item in Model)
            {
                <tr>
                    <td><img src="@item.ImageUrl" style="width:80px; height:80px" alt="Görsel Yüklenemedi" /></td>
                    <td>@item.NameSurname</td>
                    <td>@item.UserName</td>
                    <td><a href="/AdminProfile/DeleteAdminP/@item.AdminId" class="btn btn-danger"><i class="fas fa-trash"></i></a></td>
                    <td><a href="/AdminProfile/UpdateAdminP/@item.AdminId" class="btn btn-info"><i class="fas fa-edit"></i></a></td>
                </tr>
            }
        }

        else
        {
            <tr>
                <td colspan="7" class="text-center">Resim yok.</td>
            </tr>
        }
    </tbody>

</table>
<br />

@if (TempData["ErrorMessage"] != null)
{
    <div class="alert alert-danger" role="alert"> @TempData["ErrorMessage"] </div>
}

@if (TempData["SuccessMessage"] != null)
{
    <div class="alert alert-success" role="alert"> @TempData["SuccessMessage"] </div>
}

<a href="/AdminProfile/AddAdminP" class="btn btn-primary">Yeni Admin Ekle</a>

YummyProject/Views/AdminProfile/UpdateAdminp.cshtml
@model YummyProject.Models.Admin
@{
    ViewBag.Title = "UpdateAdminp";
    Layout = "~/Views/AdminLayout/Index.cshtml";
}

<h2>Admin Profili Güncelleme Sayfası</h2>
<br />

<form method="post">

    @Html.HiddenFor(x => x.AdminId)
    <label>Resim</label>
    @Html.TextBoxFor(x => x.ImageUrl, new { @class = "form-control" })
    <p class="text-danger"> @Html.ValidationMessageFor(x => x.ImageUrl) </p>
    <br />
    <label>Adı Soyadı</label>
    @Html.TextBoxFor(x => x.NameSurname, new { @class = "form-control" })
    <p class="text-danger"> @Html.ValidationMessageFor(x => x.NameSurname) </p>
    <br />
    <label>Kullanıcı Adı</label>
    @Html.TextBoxFor(x => x.UserName, new { @class = "form-control" })
    <p class="text-danger"> @Html.ValidationMessageFor(x => x.UserName) </p>
    <br />
    <label>Şifre</label>
    @Html.TextBoxFor(x => x.Password, new { @class = "form-control" })
    <p class="text-danger"> @Html.ValidationMessageFor(x => x.Password) </p>
    <br />

    <button class="btn btn-outline-info">Güncelle</button>
    <a href="@Url.Action("Index", "AdminProfile")" class="btn btn-outline-danger">İptal</a>

</form>